apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
      - name: vproapp
        image: jhonni1000/vprofileapp:V1
        ports:
        - name: vproapp-port
          containerPort: 8080
      # Create dependencies for Tomcat Deployment
      initContainers:
        # Dependency to check if MySQL Database Connection is active
        - name: init-mydb
          image: busybox
          command: ['sh', '-c', 'until nslookup vprodb; do echo waiting for mydb; sleep 2; done;']
        # Dependency to check if MySQL Database Connection is active
        - name: init-memcache
          image: busybox
          command: ['sh', '-c', 'until nslookup vpromq01; do echo waiting for mydb; sleep 2; done;']
